// <auto-generated />
using System;
using AgroRegulate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgroRegulate.Infrastructure.Migrations
{
    [DbContext(typeof(AgroDbContext))]
    [Migration("20260818120349_AddSectorTypeToFactory")]
    partial class AddSectorTypeToFactory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgroRegulate.Domain.Entities.AllocationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RequestedTons")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SalesAnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("SalesAnnouncementId");

                    b.ToTable("AllocationRequests");
                });

            modelBuilder.Entity("AgroRegulate.Domain.Entities.Factory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectorType")
                        .HasColumnType("integer");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("AgroRegulate.Domain.Entities.Quota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<decimal>("RemainingTons")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAllocatedTons")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Quotas");
                });

            modelBuilder.Entity("AgroRegulate.Domain.Entities.SalesAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableTons")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalOfferedTons")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SalesAnnouncements");
                });

            modelBuilder.Entity("AgroRegulate.Domain.Entities.AllocationRequest", b =>
                {
                    b.HasOne("AgroRegulate.Domain.Entities.Factory", null)
                        .WithMany("AllocationRequests")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroRegulate.Domain.Entities.SalesAnnouncement", null)
                        .WithMany("AllocationRequests")
                        .HasForeignKey("SalesAnnouncementId");
                });

            modelBuilder.Entity("AgroRegulate.Domain.Entities.Quota", b =>
                {
                    b.HasOne("AgroRegulate.Domain.Entities.Factory", "Factory")
                        .WithMany("Quotas")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("AgroRegulate.Domain.Entities.Factory", b =>
                {
                    b.Navigation("AllocationRequests");

                    b.Navigation("Quotas");
                });

            modelBuilder.Entity("AgroRegulate.Domain.Entities.SalesAnnouncement", b =>
                {
                    b.Navigation("AllocationRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
